### PR TITLE
[pdfx] replace import on ios pigeon file for macos

### LINKED ISSUE #358: [pdfx] Build crash on macOS with version 2.3.0 - 'Flutter.h not found'
After updating pdfx from 2.2.0 to 2.3.0 I get an error: 

```
/Users/dev/.pub-cache/hosted/pub.dartlang.org/pdfx-2.3.0/macos/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
```

#### Environment specs:
macOS 12.1
Flutter 3.3.4
pdfx 2.3.0
CocoaPods 1.11.3

**To Reproduce**
Use `pdfx: 2.3.0` as dependency in `pubspec.yaml` file and build a macOS version of the app.

**Expected behavior**
No build errors, just working like before.

**Additional information**
When _downgrading_ to `pdfx: 2.2.0` everything works fine again

### PR DESCRIPTION
**Pull request by kyle-seongwoo-jun**
fixes #358

### CODE REVIEW

**Comment by diasnrg** [comment]
Please merge this one. MacOs does not compile without it =)

**Comment by dxvid-pts** [comment]
Can confirm: macOS is working again using this patch.

**Comment by hughesyadaddy** [comment]
Guys please merge this. The PDF viewer is so perfect except this MAJOR issue with a full platform!

**Comment by ryanduffyne** [comment]
I can confirm as well that this works.  Please merge this.

**Comment by SergeShkurko** [comment]
@kyle-seongwoo-jun thanks for you contribution!
