### ISSUE TITLE
pdfx package example failing to build in latest xcode 16.3 with ios 18.4

### ISSUE THREAD

**Issue by aspirexio** [ScerIO/packages.flutter#576]
Swift Compiler Error (Xcode): Type of expression is ambiguous without a type annotation
/Users/xyz/.pub-cache/hosted/pub.dev/pdfx-2.9.0/ios/Classes/Document.swift:78:17

Swift Compiler Error (Xcode): Cannot find type 'NSColor' in scope
/Users/xyz/.pub-cache/hosted/pub.dev/pdfx-2.9.0/ios/Classes/Hooks.swift:2:10

Swift Compiler Error (Xcode): No exact matches in call to initializer
/Users/xyz/.pub-cache/hosted/pub.dev/pdfx-2.9.0/ios/Classes/SwiftPdfxPlugin.swift:367:34

**Comment by VB10** [comment]
@aspirexio you can use this branch for only ios

https://github.com/ScerIO/packages.flutter/pull/565#issuecomment-2840342290

**Comment by vicajilau** [comment]
This issue has been resolved on 2.9.1 version and it can be closed @SergeShkurko
