### ISSUE TITLE
[pdfx] Build crash on macOS with version 2.3.0 - 'Flutter.h not found'

### ISSUE THREAD

**Issue by benjamin-kraatz** [ScerIO/packages.flutter#358]
After updating pdfx from 2.2.0 to 2.3.0 I get an error: 

```
/Users/dev/.pub-cache/hosted/pub.dartlang.org/pdfx-2.3.0/macos/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
```

#### Environment specs:
macOS 12.1
Flutter 3.3.4
pdfx 2.3.0
CocoaPods 1.11.3

**To Reproduce**
Use `pdfx: 2.3.0` as dependency in `pubspec.yaml` file and build a macOS version of the app.

**Expected behavior**
No build errors, just working like before.

**Additional information**
When _downgrading_ to `pdfx: 2.2.0` everything works fine again

**Comment by amitsingh6391** [comment]
yes same issue for me

**Comment by AhmadSamerGhareebo** [comment]
Same issue

**Comment by kyle-seongwoo-jun** [comment]
Any updates?

**Comment by maxzod** [comment]
same here

**Comment by Tokenizer94** [comment]
same here

**Comment by nicolas-nunca** [comment]
Same issue

**Comment by tomekit** [comment]
Unfortunately still an issue in 2023.

**Comment by animator** [comment]
Any updates on this issue?

**Comment by milkyway044** [comment]
+1

**Comment by david1alvarez** [comment]
Just reproduced the issue and workaround. 2.3.0 is throwing the issue described, 2.2.0 has no issues

**Comment by abelokon0711** [comment]
@david1alvarez What is the workaround?

**Comment by thomasgi1** [comment]
The include in macos/Classes/messages.m generated by Pigeon is wrong. Instead of
`#import <Flutter/Flutter.h>`
it should be
`#import <FlutterMacOS/FlutterMacOS.h>`

It seems that the script scripts/pigeon.sh is buggy, because the contained sed script for patching message.m for MacOS works on the file in iOS folder:
```
...
echo "$BBlue Replace import in generated iOS pigeon file for support macOS$Color_Off"
to="#if TARGET_OS_IOS\n#import <Flutter\/Flutter.h>\n#else\n#import <FlutterMacOS\/FlutterMacOS.h>\n#endif"
from="#import <Flutter\/Flutter.h>"
sed -i "" "s/$from/$to/g" "ios/Classes/messages.m"
echo "$Green Success$Color_Off"
...
```

**Comment by kaseyrossanderson** [comment]
I don't see any releases or tags related to 2.2.0 to use in our pubspec.yaml. Is there a specific 'ref' we can use so we don't run into this issue until a new stable version is pushed out?

**Comment by milkyway044** [comment]
@kaseyrossanderson https://pub.dev/packages/pdfx/versions

`flutter pub add pdfx: 2.2.0`

**Comment by maxzod** [comment]
> The include in macos/Classes/messages.m generated by Pigeon is wrong. Instead of `#import <Flutter/Flutter.h>` it should be `#import <FlutterMacOS/FlutterMacOS.h>`
> 
> It seems that the script scripts/pigeon.sh is buggy, because the contained sed script for patching message.m for MacOS works on the file in iOS folder:
> 
> ```
> ...
> echo "$BBlue Replace import in generated iOS pigeon file for support macOS$Color_Off"
> to="#if TARGET_OS_IOS\n#import <Flutter\/Flutter.h>\n#else\n#import <FlutterMacOS\/FlutterMacOS.h>\n#endif"
> from="#import <Flutter\/Flutter.h>"
> sed -i "" "s/$from/$to/g" "ios/Classes/messages.m"
> echo "$Green Success$Color_Off"
> ...
> ```

this works for me
